"""empty message

Revision ID: 238ba270da7e
Revises: 38618002ac93
Create Date: 2023-05-13 22:20:46.875223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238ba270da7e'
down_revision = '38618002ac93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
