"""empty message

Revision ID: 902a5bd285c6
Revises: 238ba270da7e
Create Date: 2023-05-14 09:47:50.881448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902a5bd285c6'
down_revision = '238ba270da7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
