"""empty message

Revision ID: e48bb9d9ea7c
Revises: d26d4fa86267
Create Date: 2023-05-13 20:08:34.347634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48bb9d9ea7c'
down_revision = 'd26d4fa86267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint('email', 'users',  ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('email', 'users', type_='unique')
    op.drop_column('users', 'email')

    # ### end Alembic commands ###
